# Site settings
title: "BioVis 2018"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2018"
#url: "http://biovis.github.io/biovis_2016"
url: "http://biovis.net"
conferenceshort: "BioVis 2018"
eventNum: "8th"
IEEEconferencedate: "October 2018"
ISMBconferencedate: "July 9th 2018"

# Old deadlines so I remember what they're called
# When everything breaks
#IEEE_deadline_submission: "TBD"
#IEEE_deadline_notification: "TBD"
#IEEE_deadline_camera: "TBD"
#IEEE_deadline_poster: "TBD"

#ISMB_hl_and_nresearch_submission: "TBD"
#ISMB_deadline_poster: "TBD"
#ISMB_hl_and_nresearch_notiication: "TBD"

ismb_paper_submission_deadline: "January 29 2018"
ismb_paper_conditional_accept: "TBD"
ismb_paper_revised: "TBD"
ismb_paper_final_acceptance: "TBD"

biovis_paper_submission_deadline: "TBD"

ismb_abstract_submission_deadline: "April 5 2018"

ismb_poster_submission_deadline: "May 1st 2018"
ismb_poster_accept: "TBD"
ismb_poster_oral_notification: TBD"

ismb_highlights_submission_deadline: "May 4th 2018"
ismb_highlights_accept: "TBD"

bmc_submission_deadline: ""
bmc_conditional_accept: ""
bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
- posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
